# Homework 1: Basic Python, Arrays, and DataFrames

## Due Tuesday, January 24th at 11:59PM

Welcome to Homework 1! This week's homework will cover basic Python, arrays, and DataFrames. You can find additional help on these topics in [Chapter 1](https://www.inferentialthinking.com/chapters/01/what-is-data-science.html) of Computational and Inferential Thinking and [BPD 1-11](https://notes.dsc10.com/01-getting_started/tools.html) in the `babypandas` notes.


### Instructions

Remember to start early and submit often. You are given six slip days throughout the quarter to extend deadlines. See the syllabus for more details. With the exception of using slip days, late work will not be accepted unless you have made special arrangements with your instructor.

**Important**: For homeworks, the `otter` tests don't usually tell you that your answer is correct. More often, they help catch careless mistakes. It's up to you to ensure that your answer is correct. If you're not sure, ask someone (not for the answer, but for some guidance about your approach). These are great questions for office hours (the schedule can be found [here](https://dsc10.com/calendar)) or EdStem. Directly sharing answers is not okay, but discussing problems with the course staff or with other students is encouraged. 

In [2]:
!pip install babypandas

In [4]:
# Please don't change this cell, but do make sure to run it.

import matplotlib.pyplot as plt
import numpy as np
import babypandas as bpd

plt.style.use('ggplot')

## 1. Characters in Winnie-the-Pooh 🧸🍯🐷

In Lecture 1, we counted the number of times that the characters Amy, Beth, Jo, Meg, and Laurie were named in each chapter of the classic book _Little Women_. In this question, we'll look at another classic book – _Winnie-the-Pooh (1926)_ by A. A. Milne and illustrated by Ernest H. Shepard. At the start of 2022, the copyright protections of the original book (but not the Disney franchise!) expired, and so sites like Project Gutenberg are now able to post copies of the book without violating any copyright laws. [Click here](https://www.gutenberg.org/files/67098/67098-h/67098-h.htm) to read a version of the book that has all of its original illustrations!

<img src="data/illus27.jpg" width=500>

Four of the main characters in _Winnie-the-Pooh_ are Pooh (🧸), Piglet (🐷), Eeyore (🐴), and Christopher Robin (🧍).

Below, we've written code that shows the number of mentions of each of these four characters in each of the 10 chapters of the book. However, instead of displaying this information in a scatter plot, as was done in Lecture 1, we will use a bar chart.

Run the cell below to generate this bar chart. This cell contains code that hasn't yet been covered in the course.
It isn't expected that you'll understand the code, but you should be able to interpret the bar chart it generates.

In [11]:
# Open the book and split it into chapters
book_file = 'data/winnie-the-pooh.txt'
raw_book = open(book_file, encoding="utf-8").read()
end_pos = raw_book.index('*** END OF THE PROJECT GUTENBERG EBOOK WINNIE-THE-POOH ***')
chapters = raw_book[:end_pos].split('CHAPTER ')[1:]

# Find the number of words in each chapter
chapter_lengths = (np.array([len(c.split(' ')) for c in chapters]) / 100)

# Find the number of mentions per 100 words for each character and chapter
characters = bpd.DataFrame().assign(
    Chapter=np.arange(1, 11),
    Pooh=np.char.count(chapters, 'Pooh') / chapter_lengths,
    Piglet=np.char.count(chapters, 'Piglet') / chapter_lengths,
    Eeyore=np.char.count(chapters, 'Eeyore') / chapter_lengths,
    Christopher=np.char.count(chapters, 'Christopher') / chapter_lengths
)

characters.plot(kind='bar', x='Chapter', figsize=(14, 8));
plt.ylabel('Mentions per 100 words in chapter');

NameError: name 'bpd' is not defined

Looking at the bar chart, we see that the height of the bar for Pooh in Chapter 1 is 1.5 and the y-axis of this graph is “Mentions per 100 words in chapter”;  this means that 1.5 of every 100 words in Chapter 1 are `"Pooh"` (or in other words, $1.5\%$ of the words in Chapter 1 are `"Pooh"`).

**Question 1.1.**  The very first time Eeyore’s name is used in the story is in the following sentence:

> The Old Grey Donkey, Eeyore, stood by himself in a thistly corner of the forest, his front feet well apart, his head on one side, and thought about things.

In which chapter is this sentence? Assign the variable `pooh_part1` to an integer between 1 and 10.

In [21]:
pooh_part1 = 5

In [19]:
grader.check("q1_1")

NameError: name 'grader' is not defined

**Question 1.2.** Eeyore is mentioned 54 times in Chapter 6. How many times is Christopher mentioned in Chapter 6? Assign the variable `pooh_part2` to 1, 2, 3, 4, or 5 corresponding to the answer choices below. Remember to input your answer as a **number from 1-5 corresponding to the option numbers below, and not to the number of times Christopher is mentioned.** For example, if you think Christopher is mentioned 9 times, you should set `pooh_part2` to 5, not 9.

1. 1 time
1. 3 times
1. 5 times
1. 7 times
1. 9 times

In [ ]:
pooh_part2 = ...

In [ ]:
grader.check("q1_2")

**Question 1.3.** Chapter 3 is the shortest chapter with 1185 words. Chapter 8 is the longest chapter with 2962 words. Based on this information and the plot, which of the following is correct? Assign the variable `pooh_part3` to 1, 2, 3, or 4.

1. Pooh is mentioned more times in Chapter 3 than in Chapter 8. Piglet is mentioned more times in Chapter 3 than in Chapter 8.
1. Pooh is mentioned more times in Chapter 3 than in Chapter 8. Piglet is mentioned fewer times in Chapter 3 than in Chapter 8.
1. Pooh is mentioned fewer times in Chapter 3 than in Chapter 8. Piglet is mentioned more times in Chapter 3 than in Chapter 8.
1. Pooh is mentioned fewer times in Chapter 3 than in Chapter 8. Piglet is mentioned fewer times in Chapter 3 than in Chapter 8.

In [3]:
pooh_part3 = i don't know. 

In [ ]:
grader.check("q1_3")

**Question 1.4.** Which of the following is a valid conclusion we can make based off of the above plot alone? Assign `pooh_part4` to 1, 2, 3, 4, or 5. There is only one correct answer.

1. Piglet is mentioned more times in Chapter 3 than he is in Chapter 5.

1. The chapter that Pooh is mentioned the most in is Chapter 2.

1. Christopher is mentioned roughly the same number of times in each of Chapters 1, 2, and 3.

1. Pooh is mentioned roughly the same number of times in Chapters 4 and 5.

1. Christopher and Eeyore are mentioned roughly the same number of times in Chapter 10.

In [ ]:
pooh_part4 = i don't know?

In [ ]:
grader.check("q1_4")

*Note:* The tests in this section only check that you set each variable to a number in the correct range. Unlike in labs, tests in homeworks **do not** check that you answered correctly; they only check that your answer is *reasonable*, or in the correct format. To put it another way: all of your tests might pass, but that doesn't mean you'll get full credit – some of your answers may still be wrong. It's up to you to make sure that they're right!

## 2. Python Basics 🐍

**Question 2.1.** When you run the following cell, Python produces a cryptic error message.

In [ ]:
# 2023 = 2025 - 2.0

Choose the best explanation of what's wrong with the code, and then assign 1, 2, 3, or 4 to `basics_part1` below to indicate your answer.

1. The left hand side is an `int`, while the right hand side is a `float`. It should be `2023.0 = 2025 - 2.0`.

1. This is creating a variable called `2023`, which doesn't make sense because `2023` is a number.

1. The result should be written after the calculation. It should be `2025 - 2.0 = 2023`.

1. Python is not able to subtract a `float` from an `int` because they are of different data types.


<font color=red>**🚨 Important: Once you have finished this question, "comment"  out the above code cell out by replacing it with `# 2023 = 2025 - 2.0`. This will prevent the error message from appearing when your notebook is graded.**</font>

In [ ]:
basics_part1 = 2

In [ ]:
grader.check("q2_1")

**Question 2.2.** Consider the following poorly-written code.

In [1]:
three = 3
four = 4
three = four + three
three = three * four
three = three * three
three = -three

As this code executes, what values does the variable `three` take on? Assign 1, 2, 3, or 4 to `basics_part2` to indicate your answer.

1. The variable `three` takes on the values 3, 7, 28, 324, -324.

2. The variable `three` takes on the values 3, 7, 12, 36, -36.

3. The variable `three` takes on the values 3, 7, 28, 784, -784.

4. The variable `three` takes on the values 3, 7, 12, 144, -144.

In [2]:
basics_part2 = 3

In [ ]:
grader.check("q2_2")

## 3. Road Trip   🚘 

Over winter break, you went on a road trip with a friend. Now, you want to perform some calculations on data you gathered throughout your journey. Answer the questions below, using Python to perform all the intermediate calculations, such as adding, squaring, and dividing.

Note that the `math` package has not been imported. You don't need it for this question, and **you should not import it**, otherwise the autograder may produce an error.

**Question 3.1.** On the first day of the trip, your friend drove the car at three different speeds, for varying lengths of time, as shown below:

| Journey | Speed (miles per hour) | Time (hours)|
| --- | --- | --- |
| Part 1 | 34 | 2 |
| Part 2 | 47 | 1 |
| Part 3 | 65 | 4 |


Using this information, calculate the average speed, in miles per hour, at which your friend drove the car that day, and assign your answer to the variable `means_part1`. Recall from math and physics that average speed is the total distance divided by total time.

In [3]:
# Feel free to define intermediate variables to use in your solution.


total_distance = (2*34)
total_time = 2
means_part1 = (2*34)/2
means_part1

34.0

In [ ]:
grader.check("q3_1")

**Question 3.2.** On the second day of the trip, your friend drove the car three times again, but this time at the speeds and distances seen below:

| Journey | Speed (miles per hour) | Distance (miles)|
| --- | --- | --- |
| Part 1 | 34 | 2 |
| Part 2 | 47 | 1 |
| Part 3 | 65 | 4 |

Using this information, calculate the average speed, in miles per hour, at which your friend drove the car that day, and assign your answer to the variable `means_part2`. 

Note that the third column is **Distance (miles), not Time (hours).** Unlike in Question 3.1, you aren't given the amount of time that each part of the journey took; you need to compute these times yourself. To calculate the time taken for each part of the journey, divide the distance for that part by the speed for that part. Finally, add up the times for the three parts of the trip to find the total time.

In [ ]:
# Feel free to define intermediate variables to use in your solution.


total_distance2 = 1
total_time2 = 1/47                                                                       

# means_part2 = 1/1/                                                                         .  ≥ ≥       ≥≥≥≥≥≥≥≥≥≥≥≥≥≥ ≥....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................vvv,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,  ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           v                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ,m emmµµ∑
means_part2

In [ ]:
grader.check("q3_2")

**Question 3.3.** On the way back home, your friend stops at a pet store to buy an aquarium. The only one available is a rectangular tank, which unfortunately doesn't fit in the car because of your suitcases. This tank has a height of 34 inches, a width of 47 inches, and a length of 65 inches. 

Your friend thinks that the aquarium would have fit in the car with all your suitcases if it had the same volume, but was shaped as a cube instead. What would the length of each side of such an aquarium be in inches? Save your answer in the variable `means_part3`.

In [14]:
# Feel free to define intermediate variables to use in your solution.


means_part3 = np.cbrt(34*47*65)
means_part3

47.007091128653165

In [ ]:
grader.check("q3_3")

In this problem, though you calculated three different quantities in three different ways, all of your results are actually considered **means**, of various kinds!

In Question 3.1., given $n$ values $x_1, x_2, ..., x_n$, you found an *arithmetic mean*, using the formula
$${x_1+x_2+...+x_n \over n},$$
where the numerator represented total distance and the denominator represented total time. An arithmetic mean is the usual type of mean or average you're used to seeing. It turns out that you actually computed a more sophisticated arithmetic mean, known as a _weighted arithmetic mean_, $$\frac{w_1 x_1 + w_2 x_2 + ... + w_n x_n}{w_1 + w_2 + ... + w_n}$$ where the weights $w_1, w_2, w_3$ were the times travelled in each part of the journey.

In Question 3.2., given  $n$ values $x_1, x_2, ..., x_n$, you found a *harmonic mean*, using the formula
$${n \over {{1 \over x_1}+{1 \over x_2}+ ... + {1 \over x_n}}},$$ 
where the numerator represented total distance and the denominator represented total time. To calculate the total time, you needed to sum the time taken for each part of the trip, calculated using the fact that time is distance over speed. Again, it turns out that you actually computed the _weighted harmonic mean_, but this time the weights were the distances travelled. If you're curious, see the formula [here](https://en.wikipedia.org/wiki/Harmonic_mean#Weighted_harmonic_mean).

Finally in Question 3.3., given $n$ values $x_1, x_2, ..., x_n$, you found a *geometric mean*, using the formula 
$${\sqrt[n]{x_1 \cdot x_2 \cdot ... \cdot x_n}},$$ 
where each value represented a dimension of the rectangular tank. 

As you can see, there are many different notions of mean. You'll learn about some of them if you take DSC 40A!

## 4. Beverage Consumption Among Youth 🧃

In this problem, we want to quantify how *dissimilar* three different age categories (little kids, big kids, and teens) are, in terms of their beverage consumption, using three commonly consumed beverages (water, milk, and soft drinks).

The data below comes from the CDC's [Beverage Consumption Among Youth in the United States, 2013-2016](https://www.cdc.gov/nchs/products/databriefs/db320.htm).

| Percent of Total Beverage Consumption       | Little Kids (Ages 2-5)  | Big Kids (Ages 6-11)  | Teens (Ages 12-19) |
|-------------------------------------------|-------------|-----------|-----------|
| Water        | 39.5 | 41.9 | 47.0 | 
| Milk       | 32.1 | 24.4 | 14.5 | 
| Soft Drinks    | 13.0 | 20.9  | 22.3 | 

We define the **dissimilarity** between two age groups as the largest absolute difference between their 3 respective consumption percentages.

To better understand dissimilarity, consider the following hypothetical situation.
* Age group A's *consumption of water* is **10 percent more** than age group B's.
* Age group A's *consumption of milk* is **3 percent less** than age group B's.
* Age group A's *consumption of soft drinks* is **7 percent less** than age group B's.

Here, we would say the dissimilarity between age group A and age group B is 10, since 10 is larger than both 3 and 7.

**Question 4.1.** 
Using this method, compute the dissimilarity between big kids and teens.  Assign the result to the variable `dissimilarity`. Use a single expression (a single line of code) to compute the answer. Let Python perform all the arithmetic (like subtracting) rather than simplifying the expression yourself. 

*Hint:* The built-in `abs` function computes absolute values. 

In [35]:
dissimilarity =  max(abs(47-41.9),abs(14.5-24.4),abs(22.3-20.9))
dissimilarity

9.899999999999999

In [ ]:
grader.check("q4_1")

**Question 4.2.** Which pair of age groups is **most** dissimilar, according to this measurement? Assign either 1, 2, or 3 to the variable `most_dissimilar` below.

1. little kids and big kids
1. big kids and teens
1. little kids and teens

In [ ]:
most_dissimilar = 3

In [ ]:
grader.check("q4_2")

**Question 4.3.** It turns out that if we eliminated a certain one of the three beverage percentages in the table (for example, getting rid of the soft drinks row) and recalculated dissimilarities based on the remaining two percentages only, we would find the dissimilarity between each pair of age groups to be the same as if we had used all three percentages. In other words, one of the three rows of the table ends up not factoring into the calculation for dissimilarity for all three pairs of age groups.

Which percentage can be eliminated without changing the dissimilarity of any pair of age groups in the table? Assign either 1, 2, or 3 to the variable `disposable` below.

1. The consumption percentage of water.
1. The consumption percentage of milk.
1. The consumption percentage of soft drinks.

In [15]:
disposable = 2

In [ ]:
grader.check("q4_3")

## 5. Arrays 🗃️

**Question 5.1.** Make an array called `quirky_numbers` containing the following numbers (in the given order):

1. The square root of 23
2. 73 degrees, in radians
3. $3^9 + 7^5$
4. The mathematical constant of $e$ over 8: $\frac{e}{8}$
5. The base 10 logarithm of 5

*Hint:* Check out the functions constants available in the `numpy` module, which has been imported as `np`. If you're unsure of what function to use, a quick Google search should do the trick.  Do **not** import `math` or any other modules. 

*Note:* In this problem, as with all others, we'll only check that your answer is correct. There may be several valid ways to produce the correct answer.

In [26]:
quirky_numbers = np.array([np.sqrt(23),np.radians(73),3^9+7^5,e/8,np.log10(5)])
quirky_numbers

NameError: name 'e' is not defined

In [ ]:
grader.check("q5_1")

**Question 5.2.** Make an array called `likes` containing the following three strings:
- `'I like planting'`
- `'my cats'`
- `'and my family!'`

<!--
BEGIN QUESTION
name: q5_2
-->

In [47]:
likes = np.array('I like planting' + ' my cats' + ' and my family!')

likes

array('I like planting my cats and my family!', dtype='<U38')

In [44]:
grader.check("q5_2")

NameError: name 'grader' is not defined

<center><img src=data/cat_plant.jpeg width=400><a href="https://www.reddit.com/r/pottedcats/comments/xpokrc/blue_eyes/">source</a></center>


In [Lecture 3](https://dsc10.com/resources/lectures/lec03/lec03.html#String-methods), we looked at several string methods, like `upper` and `replace`. Strings have another method that we haven't seen yet, called `join`. `join` takes one argument, an array of strings, and it returns a single string. Specifically, `some_string.join(some_array)` evaluates to a new string consisting of all of elements in `some_array`, with `some_string` inserted in between each element.

For example, `'-'.join(np.array(['call', '858', '534', '2230']))` evaluates to `'call-858-534-2230'`.

**Question 5.3.** Use the array `likes` and the method `join` to make two strings:

1. `'I like planting, my cats, and my family!'` (call this one `by_comma`)
1. `'I like planting my cats and my family!'` (call this one `by_space`)

In [49]:
by_comma = likes
by_space = np.array('I like planting my cats and my family!')

# Don't change the lines below.
print(by_comma)
print(by_space)

I like planting my cats and my family!
I like planting my cats and my family!


In [ ]:
grader.check("q5_3")

Now let's get some practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *integer position*, with the position of the first element being zero. That's probably not the way you learned to count, so it's easy to get mixed up here. Be careful!

**Question 5.4.** The cell below creates an array of strings.

In [ ]:
some_strings = np.array(['flowers', '🌼', '🌸', '🌱', 'plant', 'dog', '🐶', 'cat', '🐈'])
some_strings

What is the integer position of `'🐶'` in the array? You can just type in the answer, which should be of type `int`. This is a conceptual question, not a coding question.

_Note:_ Your answer should be a **positive** integer!

In [51]:
dog_emoji_position = 6
dog_emoji_position

6

In [52]:
grader.check("q5_4")

NameError: name 'grader' is not defined

**Question 5.5.** Suppose you have an array with 500 elements. What is the integer position of the ninth-to-last element in this array? You can just type in the answer, which should be of type `int`. This is a conceptual question, not a coding question.

_Note:_ Again, your answer should be a **positive** integer!

In [53]:
ninth_last_position = 492
ninth_last_position

492

In [ ]:
grader.check("q5_5")

**Question 5.6.** Suppose you have an array with 123 elements. At what integer position is the middle element of this array? You can just type in the answer, which should be of type `int`. This is a conceptual question, not a coding question.

_Note:_ Again, your answer should be a **positive** integer!

In [54]:
mid_position = 62
mid_position

62

In [ ]:
grader.check("q5_6")

By the way, it's also possible to use negative integer positions to access elements in an array, which can be easier than using positive integer positions sometimes.  If a position is negative, you count from the end of the array rather than from the beginning. Position -1 corresponds to the last element, -2 corresponds to the second-last element, and so on. For instance, to find the third-to-last element of `some_strings`, we could use:

In [ ]:
some_strings[-3]

## 6. DSC 10 Enrollments 📈

It's time to get to know your classmates! The third column of the table below shows how many UCSD undergraduate students in this quarter's offering of DSC 10 come from each of the university's seven colleges. It looks like Sixth College is the most popular, with 81 students. The last column shows how many of these students are DSC majors. Even though Sixth College is the most popular, none of the DSC 10 students from the college are DSC majors!

For comparison's sake, we also have the corresponding data from the Fall 2022 offering of DSC 10. You can see that most DSC majors take this course in the fall!

Throughout this problem, we'll assume that all students in DSC 10 come from one of the seven colleges in the table.

|College|Fall 22 Students|Fall 22 DSC Major Students|Winter 23 Students|Winter 23 DSC Major Students|
|---|---|---|---|---|
|Seventh|37|21|45|2|
|Sixth|93|54|81|0|
|Roosevelt|67|39|46|4|
|Warren|61|40|41|1|
|Marshall|62|32|50|1|
|Muir|38|27|42|2|
|Revelle|52|31|43|2|

In this question, we'll be working with the data from this table as *arrays*. Here are those arrays:


In [18]:
students_22 = np.array([37, 93, 67, 61, 62, 38, 52])
students_22

array([37, 93, 67, 61, 62, 38, 52])

In [17]:
majors_22 = np.array([21, 54, 39, 40, 32, 27, 31])
majors_22

array([21, 54, 39, 40, 32, 27, 31])

In [21]:
students_23 = np.array([45, 81, 46, 41, 50, 42, 43])
students_23

array([45, 81, 46, 41, 50, 42, 43])

In [22]:
majors_23 = np.array([2, 0, 4, 1, 1, 2, 2])
majors_23

array([2, 0, 4, 1, 1, 2, 2])

Remember, the `numpy` package (`np` for short) provides many handy functions for working with arrays. These are specifically designed to work with arrays and are faster than using Python's built-in functions. 

Some frequently used array functions are `np.min()`, `np.max()`, `np.sum()`, `np.abs()`, and `np.round()`. There are many more, which you can browse by typing `np.` into a code cell and hitting the *tab* key, or by looking at the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

**Question 6.1.** Assign `enrolled_22` and `enrolled_23` to the number of students that were enrolled in DSC 10 in Fall 2022 and Winter 2023, respectively.

In [60]:
enrolled_22 = majors_22
enrolled_23 = majors_23

# Don't change the lines below.
print('Students in Fall 2022:', enrolled_22)
print('Students in Winter 2023:', enrolled_23)

Students in Fall 2022: [21 54 39 40 32 27 31]
Students in Winter 2023: [2 0 4 1 1 2 2]


In [ ]:
grader.check("q6_1")

**Question 6.2.** How many non-DSC major students from the Fall 2022 offering of DSC 10 came from each of the seven colleges? Your answer should be an array called `non_majors_22`, with the colleges in the same order as they appear in the table above. For instance, the first element of `non_majors_22` should be the number of non-DSC majors in the Fall 2022 offering of DSC 10 who were in Seventh College.

Similarly, how many non-DSC major students from the Winter 2023 offering of DSC 10 came from each of the seven colleges? Your answer should be an array called `non_majors_23`, with the colleges in the same order as they appear in the table above. 


In [19]:
non_majors_22 = students_22 - majors_22

non_majors_22

array([16, 39, 28, 21, 30, 11, 21])

In [ ]:
grader.check("q6_2_1")

In [23]:
non_majors_23 = students_23 - majors_23
non_majors_23

array([43, 81, 42, 40, 49, 40, 41])

In [ ]:
grader.check("q6_2_2")

**Question 6.3.** What percentage of Fall 2022 DSC 10 students from each college were DSC majors? Your answer should be an array called `percent_majors_22`, with the colleges in the same order as they appear in the table above, and with percentages rounded to two decimal places.

Similarly, what percentage of Winter 2023 DSC 10 students from each college were DSC majors? Your answer should be an array called `percent_majors_23`, with the colleges in the same order as they appear in the table above, and with percentages rounded to two decimal places.

In [32]:
(majors_22/students_22)*100

array([56.75675676, 58.06451613, 58.20895522, 65.57377049, 51.61290323,
       71.05263158, 59.61538462])

In [33]:
percent_majors_22 = np.round((majors_22/students_22)*100,2)
percent_majors_22

array([56.76, 58.06, 58.21, 65.57, 51.61, 71.05, 59.62])

In [ ]:
grader.check("q6_3_1")

In [35]:
percent_majors_23 = np.round((majors_23/students_23)*100,2)
percent_majors_23

array([4.44, 0.  , 8.7 , 2.44, 2.  , 4.76, 4.65])

In [36]:
grader.check("q6_3_2")

NameError: name 'grader' is not defined

**Question 6.4.** For each college, what is the absolute difference in the percentage of students enrolled in DSC 10 that are DSC majors from Fall 2022 to Winter 2023? Use `percent_majors_22` and `percent_majors_23` to create an array called `abs_differences`, with the colleges in the same order as they appear in the table above. Make sure the values in your answer are rounded to two decimal places.

_Note:_ You _don't_ need to round again.

In [37]:
abs_differences = np.abs(percent_majors_22-percent_majors_23)
abs_differences

array([52.32, 58.06, 49.51, 63.13, 49.61, 66.29, 54.97])

In [ ]:
grader.check("q6_4")

For your convenience, we repeat the table from the start of the question below.

|College|Fall 22 Students|Fall 22 DSC Major Students|Winter 23 Students|Winter 23 DSC Major Students|
|---|---|---|---|---|
|Seventh|37|21|45|2|
|Sixth|93|54|81|0|
|Roosevelt|67|39|46|4|
|Warren|61|40|41|1|
|Marshall|62|32|50|1|
|Muir|38|27|42|2|
|Revelle|52|31|43|2|



**Question 6.5.** You might say that the most consistent college is the one with the smallest absolute difference in the percentage of students enrolled in DSC 10 that are DSC majors across the two years. Find the smallest value in the `abs_differences` array and save it as `smallest_abs_diff`. Referring back to the table, try to figure out which college that is. Assign `most_consistent_college` to the name of that college (as a string), exactly as it's displayed in the table.

_Note:_ You can type the name of the college manually.

In [48]:
smallest_abs_diff = np.min(abs_differences)
most_consistent_college = 'Roosevelt'

print(smallest_abs_diff)

print(most_consistent_college)

49.510000000000005
Roosevelt


In [42]:
grader.check("q6_5")

NameError: name 'grader' is not defined

## 7. World Cup 🌎🥤⚽

The Federale Internationale de Football Association (FIFA) is the international governing body of soccer (or football, depending where you're from). FIFA has 209 member countries, making it one of the most respected sports organizations in the world. The organization has hosted an international tournament, called the World Cup, every four years since 1930, except for during WWII. The most recent one took place in 2022 in Qatar. 

<img src="data/messi.jpeg" width=60%>

The file `world_cup.csv` in the `data/` directory contains information about every World Cup tournament that has ever taken place. Its columns are:

| Column      | Description |
| ----------- | ----------- |
| `'Year'`      | Year of World Cup     |
| `'Host'`   | Name of host country        |
| `'Total Attendance'` | Total number of people in attendance across all matches  |
| `'Matches'` | Total number of matches played |
| `'Teams'` | The  total number of teams that competed in the World Cup |
| `'First'` | Winner of the World Cup |
| `'Second'` | The team in second place | 
| `'Third'` | The team in third place|
| `'Fourth'` | The team in fourth place |

**Question 7.1.** Read this file into a DataFrame called `world_cup`. 

In [5]:
world_cup = bpd.read_csv('data/world_cup.csv')
world_cup

Year          Host  Total Attendance  Matches  Teams         First  \
0   1930       Uruguay            590549       18     13       Uruguay   
1   1934         Italy            363000       17     16         Italy   
2   1938        France            375700       18     15         Italy   
3   1950        Brazil           1045246       22     13       Uruguay   
4   1954   Switzerland            768607       26     16  West Germany   
..   ...           ...               ...      ...    ...           ...   
17  2006       Germany           3359439       64     32         Italy   
18  2010  South Africa           3178856       64     32         Spain   
19  2014        Brazil           3429873       64     32       Germany   
20  2018        Russia           3031768       64     32        France   
21  2022         Qatar           3404252       64     32     Argentina   

            Second          Third      Fourth  
0        Argentina  United States  Yugoslavia  
1   Czechoslovakia        Germany     Austria  
2          Hungary         Brazil      Sweden  
3           Brazil         Sweden       Spain  
4          Hungary        Austria     Uruguay  
..             ...            ...         ...  
17          France        Germany    Portugal  
18     Netherlands        Germany     Uruguay  
19       Argentina    Netherlands      Brazil  
20         Croatia        Belgium     England  
21          France        Croatia     Morocco  

[22 rows x 9 columns]

In [2]:
grader.check("q7_1")

NameError: name 'grader' is not defined

**Question 7.2.** Add a column to `world_cup` called `Average_Attendance` that contains the average number of attendees per match in each World Cup tournament. Do not round.

In [9]:

world_cup = np.insert(column = "Average_Attendence")
Average_Attendence = 
world_cup

NameError: name 'Average_Attendence' is not defined

In [ ]:
grader.check("q7_2")

**Question 7.3.** Create a new DataFrame, `world_cup_by_year`, by setting the index of `world_cup` to `'Year'`. Don't change `world_cup`.

In [ ]:
world_cup_by_year = ...
world_cup_by_year

In [ ]:
grader.check("q7_3")

You should think about why we've chosen to set the index to `'Year'`, instead of any other column.

**Question 7.4.** Where was the 1998 World Cup held, and what was the average attendance per match that year? Assign your results to `location_98` and `average_98`, respectively.

Don't type in the answers by hand; get Python to extract this information for you.

In [ ]:
location_98 = ...
average_98 = ...

# Don't change the lines below.
print('Location:', location_98)
print('Average attendance per match:', average_98)

In [ ]:
grader.check("q7_4")

**Question 7.5.** Since the first tournament in 1930, more and more countries have joined FIFA, which means more matches are played in each tournament. Using DataFrame operations, find the number of World Cup tournaments that had more than 50 matches. Assign the number of such tournaments to `over_50_matches`. 

In [ ]:
over_50_matches = ...
over_50_matches

In [ ]:
grader.check("q7_5")

**Question 7.6.** Assign `eighth_highest_attendance` to the eighth highest total attendance of all World Cup tournaments. Assign the year where this attendance occurred, to `eighth_highest_year`.

Again, don't type in these values by hand; get Python to extract this information for you.

In [ ]:
eighth_highest_attendance = ...
eighth_highest_year = ...

# Don't change the lines below.
print('Attendance:', eighth_highest_attendance)
print('Year:', eighth_highest_year)

In [ ]:
grader.check("q7_6")

**Question 7.7.** There are two countries tied for having hosted the most tournaments, France and Italy, having hosted 2 times each. 

Find out which country was a more popular host, by finding the sum of the `'Total Attendance'` for each country, for the two times it was a host. Assign these totals to `france_total_attendance` and `italy_total_attendance`.

In [ ]:
france_total_attendance = ...
italy_total_attendance = ...

# Don't change the lines below.
print('France:', france_total_attendance)
print('Italy: ', italy_total_attendance)

In [ ]:
grader.check("q7_7")

**Question 7.8.** Now find out which country was the most popular host overall, by finding the sum of the `Total Attendance` for each country that has ever hosted a World Cup tournament. Assign the name of the host country with the greatest total attendance across all World Cups to `most_popular_host`.

*Hint*: Our solution for this question used only one line of code (thanks, `groupby`)!

In [ ]:
most_popular_host = ...
most_popular_host

In [ ]:
grader.check("q7_8")

**Question 7.9.** Determine which country won the World Cup championship the most number of times. Assign this country to `most_frequent_winner`, and the number of times this country won to `win_count`.

Again, don't type in these values by hand; get Python to extract this information for you.

In [ ]:
most_frequent_winner = 
win_count = ...

# Don't change the lines below.
print('Most frequent winner:', most_frequent_winner)
print('Number of World Cup championships: ', win_count)

In [ ]:
grader.check("q7_9")

## Finish Line: Almost there, but make sure to follow the steps below to submit! 🏁

1. Make sure to comment out the code in Question 3.1 that causes an error.
2. Select `Kernel -> Restart & Run All` to ensure that you have executed all cells, including the test cells. 
2. Read through the notebook to make sure all cells ran and all tests passed.
3. Run the cell below to run all tests, and make sure that they all pass.
4. Download your notebook using `File -> Download as -> Notebook (.ipynb)`, then upload your notebook to Gradescope.
5. Stick around while the Gradescope autograder grades your work. Make sure you see that all tests have passed on Gradescope.
6. Check that you have a confirmation email from Gradescope and save it as proof of your submission. 

With homeworks, unlike with labs, the grade you see on Gradescope is **not your final score**. We will run correctness tests after the assignment's due date has passed.

In [ ]:
grader.check_all()